version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: finance_analysis_dashboard_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: finance_analysis_dashboard_db
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
